### ISSUE TITLE
v0.1.0 Release Checklist for ServerlessLLM

### ISSUE THREAD

**Issue by future-xy** [ServerlessLLM/ServerlessLLM#11]
### Release Preparation Checklist

- [ ] **Features**
  - Storage-aware model loading scheduler
  - Live-migration support for vLLM backend
- [ ] **PyPI Release**
- [ ] **GitHub Actions: Automatic Publishing to PyPI**
- [ ] **GitHub Actions: Automated Testing**
- [ ] **Documentation Improvement**  
- [ ] **Testing and Benchmarking**
